version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/study-game-0.0.1-SNAPSHOT.jar study-game-0.0.1-SNAPSHOT.jar

artifacts:
  files:
    - study-game-0.0.1-SNAPSHOT.jar
    - .ebextensions/**/*