phases:
  install:
    runtime-versions:
      java: openjdk8
  post_build:
    commands:
      - mvn package
      - mv target/ROOT.war ROOT.war
      artifacts:
        files:
          - ROOT.war
          - .ebextensions/**/*